## Importe

In [1]:
import numpy as np
import pandas as pd
import string

In [2]:
import re
from collections import Counter

In [3]:
!pip install pdfplumber
import pdfplumber

Requirement already satisfied: pdfplumber in c:\users\amydu\anaconda3\lib\site-packages (0.11.7)
Requirement already satisfied: pdfminer.six==20250506 in c:\users\amydu\anaconda3\lib\site-packages (from pdfplumber) (20250506)
Requirement already satisfied: Pillow>=9.1 in c:\users\amydu\anaconda3\lib\site-packages (from pdfplumber) (11.1.0)
Requirement already satisfied: pypdfium2>=4.18.0 in c:\users\amydu\anaconda3\lib\site-packages (from pdfplumber) (5.0.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\amydu\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\amydu\anaconda3\lib\site-packages (from pdfminer.six==20250506->pdfplumber) (44.0.1)
Requirement already satisfied: cffi>=1.12 in c:\users\amydu\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in c:\users\amydu\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.21)

## Einlesen der PDF-Texte

### EWMS

In [4]:
#Initialisierung eines leeren Textes
EWMS=""
#Dokument mithilfe des PDF-Readers öffnen
with pdfplumber.open("Skript_EWMS_Sommer23.pdf") as pdf:
    for page in pdf.pages:
        #Text von den PDF-Seiten auslesen
        page_text =page.extract_text()
        #Text der jeweiligen Seiten an den leeren Text anhängen
        EWMS+=page_text

In [5]:
#Ersetzen der Punkte aus dem Skript durch den Buchstaben e, da dies der häufigste Buchstabe im Alphabet ist
punkte=EWMS[5]
EWMS = EWMS.replace(punkte,'')

In [6]:
EWMS = re.sub(r'[^a-zA-Z]', '', EWMS).lower()

In [7]:
Paare=[EWMS[i:i+2] for i in range(len(EWMS)-1)]
AnzahlEWMS=Counter(Paare)

### Analysis1

In [8]:
#Initialisierung eines leeren Textes
Ana=""
#Dokument mithilfe des PDF-Readers öffnen
with pdfplumber.open("Ana1Skript.pdf") as pdf:
    for page in pdf.pages:
        #Text von den PDF-Seiten auslesen
        page_text =page.extract_text()
        #Text der jeweiligen Seiten an den leeren Text anhängen
        Ana+=page_text

In [9]:
Ana = Ana.replace(punkte,'')
Ana = re.sub(r'[^a-zA-Z]', '', Ana).lower()

In [10]:
Paare=[Ana[i:i+2] for i in range(len(Ana)-1)]
AnzahlAna=Counter(Paare)

## Anlegen des dataFrames

In [11]:
alphabet=list(map(chr, range(97, 123)))

In [12]:
B2=[]
for i in range(26):
    for j in range (26):
        B2.append(alphabet[j])
B1=[]
for i in range(26):
    for j in range(26):
        B1.append(alphabet[i])

In [13]:
Index=range(0,676)

In [14]:
Buchstabe1=pd.Series(B1,index=Index)
Buchstabe2=pd.Series(B2,index=Index)

In [15]:
Daten=pd.concat([Buchstabe1,Buchstabe2],axis=1)
Spalten=['Buchstabe1','Buchstabe2']
Daten.columns=Spalten
Daten['Buchstaben']=Daten['Buchstabe1']+Daten['Buchstabe2']

In [16]:
Daten.head()

  Buchstabe1 Buchstabe2 Buchstaben
0          a          a         aa
1          a          b         ab
2          a          c         ac
3          a          d         ad
4          a          e         ae

## absolute Häufigkeiten

In [17]:
# EWMS
AnzE=[]
for i in range(len(Daten['Buchstaben'])):
    if AnzahlEWMS[Daten['Buchstaben'][i]]>0:
        AnzE.append(AnzahlEWMS[Daten['Buchstaben'][i]])
    else:
        AnzE.append(0)

In [18]:
# Ana
AnzA=[]
for i in range(len(Daten['Buchstaben'])):
    if AnzahlAna[Daten['Buchstaben'][i]]>0:
        AnzA.append(AnzahlAna[Daten['Buchstaben'][i]])
    else:
        AnzA.append(0)

In [19]:
Daten['absH_EWMS']=AnzE
Daten['absH_Ana']=AnzA

In [20]:
Daten.head()

  Buchstabe1 Buchstabe2 Buchstaben  absH_EWMS  absH_Ana
0          a          a         aa         95       150
1          a          b         ab        397       530
2          a          c         ac        233       350
3          a          d         ad         68       131
4          a          e         ae         42        42

## relative Häufigkeiten

In [21]:
#EWMS
sumE=0
relativeHäufE=[]

for i in range(len(Daten['Buchstaben'])):
    sumE+=Daten['absH_EWMS'][i]
for i in range(len(Daten['Buchstaben'])):
    relativeHäufE.append(Daten['absH_EWMS'][i]/sumE)
Daten['relH_EWMS']=relativeHäufE

#Ana
sumA=0
relativeHäufA=[]

for i in range(len(Daten['Buchstaben'])):
    sumA+=Daten['absH_Ana'][i]
for i in range(len(Daten['Buchstaben'])):
    relativeHäufA.append(Daten['absH_Ana'][i]/sumA)
Daten['relH_Ana']=relativeHäufA

In [22]:
Daten.head()

  Buchstabe1 Buchstabe2 Buchstaben  absH_EWMS  absH_Ana  relH_EWMS  relH_Ana
0          a          a         aa         95       150   0.001593  0.001411
1          a          b         ab        397       530   0.006656  0.004986
2          a          c         ac        233       350   0.003906  0.003293
3          a          d         ad         68       131   0.001140  0.001233
4          a          e         ae         42        42   0.000704  0.000395

## Umwandeln in csv-Datei

In [23]:
Daten.to_csv('AndereDatengrundlage.csv', sep='\t')