# Importe

In [253]:
import pandas as pd

# Datei

In [254]:
spalten_namen=['Buchstabe1','Buchstabe2', 'Quelle1_abs', 'Quelle2_abs', 'Quelle3_abs', 'Quelle4_abs', 'Quelle5_abs', 'Quelle1_rel', 'Quelle2_rel', 'Quelle3_rel', 'Quelle4_rel', 'Quelle5_rel']
data=pd.read_csv("BigramWhk_klein.txt",sep='\t',header=None, names=spalten_namen)
data.head()

,Buchstabe1,Buchstabe2,Quelle1_abs,Quelle2_abs,Quelle3_abs,Quelle4_abs,Quelle5_abs,Quelle1_rel,Quelle2_rel,Quelle3_rel,Quelle4_rel,Quelle5_rel
0,a,a,1597,819,10,13204,31795,0.000328,0.000341,0.000102,0.000610,0.000968
1,a,b,97173,48575,2114,565462,809927,0.019952,0.020247,0.021586,0.026117,0.024666
2,a,c,201159,98185,4453,1094065,1353367,0.041303,0.040925,0.045470,0.050532,0.041215
3,a,d,183511,83926,4205,739787,1268700,0.037680,0.034981,0.042938,0.034169,0.038637
4,a,e,10454,4805,61,29875,91930,0.002146,0.002003,0.000623,0.001380,0.002800

In [255]:
wkeit=data['Quelle1_rel']

In [256]:
B1=data['Buchstabe1']
B2=data['Buchstabe2']

In [257]:
neuerDataframe=pd.DataFrame(index=B2[0:26],columns=B2[0:26])
neuerDataframe.index.name=None
neuerDataframe.head()

Buchstabe2,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [267]:
t=[]
for i in range (0,len(data),26):
    t.append(wkeit[i:i+26])
t = [list(x) for x in t]

In [269]:
for i in range (26):
    neuerDataframe.loc[B2[0:26][i]]=t[i]

In [270]:
neuerDataframe.head()

Buchstabe2,a,b,c,d,e,f,g,h,i,j,...,q,r,s,t,u,v,w,x,y,z
a,0.000328,0.019952,0.041303,0.03768,0.002146,0.007886,0.022827,0.001708,0.049236,0.001714,...,0.000584,0.123509,0.088293,0.14587,0.013383,0.021664,0.007352,0.003158,0.034176,0.002091
b,0.100178,0.009521,0.000835,0.000781,0.281322,0.000055,0.000041,0.000241,0.064085,0.004002,...,0.0,0.048431,0.03206,0.005859,0.099275,0.001353,0.000835,0.0,0.099839,0.000018
c,0.129175,0.000031,0.017455,0.000168,0.174018,0.000011,0.000001,0.137607,0.065581,0.000002,...,0.001382,0.038818,0.006874,0.095016,0.039146,0.000004,0.000011,0.000001,0.010818,0.000178
d,0.087141,0.001267,0.001895,0.020462,0.29259,0.001446,0.015421,0.001573,0.172009,0.001554,...,0.000764,0.037288,0.048985,0.001223,0.047875,0.009187,0.005143,0.000001,0.017842,0.000134
e,0.068156,0.004812,0.04272,0.105971,0.03682,0.013265,0.010967,0.002095,0.015328,0.000356,...,0.002467,0.192587,0.119575,0.039504,0.00185,0.020324,0.018379,0.014892,0.015838,0.000832

In [272]:
B2[0:26].duplicated().any()
list(neuerDataframe.index) == list(B2[0:26])

list

In [277]:
pd.set_option('display.expand_frame_repr', False)
print(neuerDataframe)

Buchstabe2         a         b         c         d         e         f         g         h         i         j         k         l         m         n         o         p         q         r         s         t         u         v         w         x         y         z
a           0.000328  0.019952  0.041303   0.03768  0.002146  0.007886  0.022827  0.001708  0.049236  0.001714   0.01253  0.100978  0.030956  0.203222  0.000498  0.017956  0.000584  0.123509  0.088293   0.14587  0.013383  0.021664  0.007352  0.003158  0.034176  0.002091
b           0.100178  0.009521  0.000835  0.000781  0.281322  0.000055  0.000041  0.000241  0.064085  0.004002  0.000041  0.118209  0.001192  0.000318  0.115099  0.000224       0.0  0.048431   0.03206  0.005859  0.099275  0.001353  0.000835       0.0  0.099839  0.000018
c           0.129175  0.000031  0.017455  0.000168  0.174018  0.000011  0.000001  0.137607  0.065581  0.000002  0.049474  0.036456   0.00007  0.000071  0.182322  0.000023  0.001382  0.038818  0.006874  0.095016  0.039146  0.000004  0.000011  0.000001  0.010818  0.000178
d           0.087141  0.001267  0.001895  0.020462   0.29259  0.001446  0.015421  0.001573  0.172009  0.001554  0.000194  0.014287  0.010375  0.007916  0.073711  0.000367  0.000764  0.037288  0.048985  0.001223  0.047875  0.009187  0.005143  0.000001  0.017842  0.000134
e           0.068156  0.004812   0.04272  0.105971   0.03682  0.013265  0.010967  0.002095  0.015328  0.000356  0.003867  0.045473  0.028775  0.122188  0.006973  0.015881  0.002467  0.192587  0.119575  0.039504   0.00185  0.020324  0.018379  0.014892  0.015838  0.000832
f           0.078697  0.000088  0.000139  0.000039  0.113361  0.098028  0.000481  0.000044  0.165545  0.000081  0.000264  0.029137  0.000618  0.000236    0.2771   0.00003       0.0  0.110178   0.00409  0.056762  0.042578  0.000053  0.000158  0.000005  0.004183  0.000015
g            0.10429   0.00026  0.000044  0.001105  0.234041  0.000603  0.017491  0.146894  0.073519  0.000027  0.000132  0.026498  0.002592  0.041177  0.075207   0.00024  0.000009  0.102137  0.036081  0.014014  0.047803  0.000023  0.000473   0.00001  0.011145  0.000046
h           0.185717  0.001362  0.000215   0.00095  0.511395  0.000274   0.00007  0.000186  0.114788  0.000012  0.000138  0.003039  0.001994  0.006174  0.094428  0.000139  0.000063  0.015684  0.004194  0.026173  0.010084  0.000067    0.0012       0.0  0.005219  0.000005
i           0.032501  0.007391  0.083918  0.052969  0.041088  0.014371  0.030039  0.000154   0.00027  0.000299  0.007185  0.058668  0.029525  0.265628  0.074378  0.008185  0.000722  0.034059  0.107285  0.110597  0.001342  0.027695  0.000182  0.002301  0.000178  0.006267
j           0.076272  0.000076  0.000472  0.000533  0.182748  0.000122       0.0  0.000046  0.021131  0.000152  0.000655  0.000167  0.000776  0.000441  0.333815  0.000076       0.0  0.000061  0.000152  0.000198  0.379777   0.00003       0.0       0.0  0.000061  0.000091
k           0.029505  0.002603   0.00028  0.002247  0.431235   0.00247  0.001684  0.006357  0.168778  0.000138  0.001802  0.029658  0.002026  0.053307  0.013344  0.001608       0.0  0.009142  0.108493  0.003077  0.005108  0.000662  0.003398  0.000003  0.017592  0.000038
l           0.120975  0.002475  0.002108   0.06728    0.1856  0.010282  0.001298  0.000597  0.150288  0.000031  0.006325  0.150562  0.007313  0.001098  0.077438  0.006089  0.000014  0.002303  0.037398  0.024885  0.025757  0.006593  0.002232  0.000014  0.082488  0.000237
..               ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...
o           0.009065  0.010033  0.017987  0.019221    0.0044  0.106928  0.009162  0.002964  0.011443  0.001132  0.009821  0.044158  0.073561  0.198784  0.028896  0.028004  0.000126  0.160424  0.036747  0.049044  0.097561  0.024642  0.037777  0.001324  0.004525  0.000961
p           0.139065  0.000767  0.000263   0.00028  0.189612  0.000545  0.002055  0.027721  0.050494  0.000115  0.000545   0.11016  0.004901  0.000228  0.137574  0.056333  0.000007  0.162294  0.022757  0.027994  0.044105  0.000003  0.000292  0.000001  0.006601   0.00003
q           0.000508  0.000132       0.0  0.000019  0.000038  0.000038  0.000019       0.0   0.01435       0.0       0.0  0.000056       0.0  0.000019  0.000019       0.0  0.000056       0.0  0.000056  0.000132  0.969796  0.000113  0.000038       0.0       0.0       0.0
r           0.099156   0.00439  0.020642  0.029961   0.24705  0.004288  0.016576  0.001969  0.098174  0.000076  0.024681  0.013479  0.022322  0.027553  0.103058  0.006891  0.000139  0.017127  0.073606  0.057182  0.017202   0.01744  0.001888  0.000068  0.032528  0.000291
s           0.067841  0.002012  0.024315  0.003366  0.149185  0.002071  0.000293  0.058233  0.096994  0.000024  0.010241  0.012115  0.009502  0.003619  0.061005   0.03159  0.001432  0.002283  0.071585  0.204411  0.044026  0.000235  0.003532       0.0  0.006412  0.000146
t           0.058913  0.001045  0.004153  0.000344  0.135707  0.000737  0.000505  0.326356  0.123079  0.000015  0.000105  0.010274  0.004229  0.001757  0.125325  0.000347  0.000002  0.046084  0.047246  0.020655   0.02131  0.000149  0.008368  0.000004  0.021815  0.001107
u           0.034956  0.029516  0.048803  0.034487  0.044319  0.006149  0.041328   0.00034  0.031154   0.00025   0.00204  0.090762  0.035867  0.118862  0.003174  0.046203  0.000194  0.140014  0.133844  0.145329  0.000143  0.000936  0.000391  0.001202  0.004812  0.001061
v           0.074337  0.000002  0.000653  0.000103  0.611411  0.000002  0.000142  0.000006  0.248016  0.000003  0.000037  0.000265  0.000017  0.000322  0.049076       0.0       0.0  0.000781  0.000957  0.000063  0.001325  0.000177       0.0       0.0  0.005109  0.000005
w           0.192462  0.001101  0.000493  0.002967  0.154981  0.000566  0.000046   0.17524  0.201739       0.0   0.00132  0.007777  0.001682  0.052088  0.139845  0.000283  0.000008  0.015427  0.025177   0.00292  0.000122  0.000002  0.000021  0.000001  0.005111   0.00001
x           0.086901  0.000423  0.087141   0.00001  0.143425  0.002575  0.000029  0.022614  0.086651       0.0       0.0  0.001508  0.000778  0.000183  0.016811  0.283825  0.001124  0.000038  0.000913  0.165002  0.027417   0.00097  0.004333  0.001518  0.003862   0.00001
y           0.022321  0.008728  0.011317  0.005543  0.214845  0.001344  0.001334  0.001203  0.047677  0.000052  0.000907  0.020462  0.030909  0.021311  0.094557  0.013188  0.000012  0.018431  0.104762  0.016541  0.001674  0.000661  0.007258  0.000195  0.000073  0.001658
z           0.197851  0.005721   0.00065  0.001836  0.413889  0.000211  0.002405  0.009052  0.122735  0.000033  0.003234  0.017032  0.006566  0.001739  0.055224  0.002357  0.000374  0.001885  0.002373  0.002064  0.015391  0.002064  0.002974       0.0  0.022363  0.053648

[26 rows x 26 columns]

In [280]:
neuerDataframe.to_excel('formatierte Tabelle.xlsx',sheet_name='Tabelle1')